
sudo: required

branches:
  only:
    - master
    - /20(1[7-9]|2[0-9])[0-1][0-9][0-3][0-9]/

services: docker

install: true

language: C

jobs:
  include:
   - stage: build-base
     script: scripts/build-base.sh
   - stage: build-base
     script: scripts/build-builder.sh
   - stage: build-container
     script: scripts/build-data-container-now.sh
