ARG DOCKER_TAG=latest
FROM opentransport/pelias-data-container-base:$DOCKER_TAG

RUN /bin/bash -c "source /mnt/tools/scripts/getdata.sh"

EXPOSE 9200
EXPOSE 9300

CMD /etc/init.d/elasticsearch start && sleep 10000d
